name: Docker Image CI publish a docker image.

on:
  push:
    branches:
      - "deploy"

jobs:

  build-publish-deploy:
    name: build and push docker
    runs-on: ubuntu-latest
    steps:

    - name: checkout to main
      uses: actions/checkout@v2
      with:
        ref: deploy

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1


    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Build and push hash tagged image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE }}:${{ github.head_ref }}.${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE }}:latest
        cache-to: type=inline
        
    - name: Build and push latest image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE }}:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE }}:latest
        cache-to: type=inline
